#%RAML 1.0 DataType
type: object
displayName: OffenseType
uses:
  types: ../../libraries/types.raml
properties:
  description:
    type: string
    description: Description of offence
  code:
    type: string
    description: Code of offenseType
  amount:
    type: types.Money
    description: Amount due for offenseType
