#%RAML 1.0 DataType
type: object
displayName: ParkingSticker
uses:
  types: ../../libraries/types.raml
properties:
  parkingArea:
    type: types.ParkingAreaCode
  receptionMethod:
    type: types.ReceptionMethod
  postalCode:
    type: types.PostalCode
    description: Canadian postal code to send sticker to, required if reception method is postal
    required: false
  email:
    type: types.Email
    description: Email to send sticker to, required if reception method is email
    required: false
  parkingPeriod:
    type: types.ParkingPeriod
    description: Period of access pass validity
