#%RAML 1.0 DataType
type: object
displayName: ReportPeriodData
uses:
  types: ../../libraries/types.raml
properties:
  dimensions:
      type: types.ReportDimensionData[]
  metrics:
      type: types.ReportMetricData[]
