#%RAML 1.0 Library
types:
  Date: !include ../types/times/date.raml
  Day: !include ../types/times/day.raml
  TimeOfDay: !include ../types/times/time-of-day.raml

  PostalCode: !include ../types/locations/postal-code.raml

  Email: !include ../types/communications/email.raml

  Money: !include ../types/funds/money.raml
  BillId: !include ../types/funds/bill-id.raml
  BillType: !include ../types/funds/bill-type.raml
  Bill: !include ../types/funds/bill.raml

  AccountId: !include ../types/accounts/account-id.raml
  AccountIdObject: !include ../types/accounts/account-id-object.raml

  Sex: !include ../types/users/sex.raml
  User: !include ../types/users/user.raml

  LicensePlate: !include ../types/cars/license-plate.raml
  Car: !include ../types/cars/car.raml

  ReceptionMethod: !include ../types/parkings/reception-method.raml
  AccessStatus: !include ../types/parkings/access-status.raml
  AccessStatusObject: !include ../types/parkings/access-status-object.raml
  ParkingAreaCode: !include ../types/parkings/parking-area-code.raml
  ParkingStickerCode: !include ../types/parkings/parking-sticker-code.raml
  ParkingStickerCodeObject: !include ../types/parkings/parking-sticker-code-object.raml
  ParkingSticker: !include ../types/parkings/parking-sticker.raml

  OffenseType: !include ../types/offenses/offense-type.raml
  OffenseValidation: !include ../types/offenses/offense-validation.raml
