#%RAML 1.0 Library
types:
  Date: !include ../types/time/date.raml
  Day: !include ../types/time/day.raml

  PostalCode: !include ../types/location/postal-code.raml

  Email: !include ../types/communication/email.raml

  AccountId: !include ../types/account/account-id.raml
  AccountIdObject: !include ../types/account/account-id-object.raml

  Sex: !include ../types/user/sex.raml
  User: !include ../types/user/user.raml

  LicensePlate: !include ../types/car/license-plate.raml
  Car: !include ../types/car/car.raml

  ReceptionMethod: !include ../types/parking/reception-method.raml
  AccessStatus: !include ../types/parking/access-status.raml
  AccessStatusObject: !include ../types/parking/access-status-object.raml
  ParkingAreaCode: !include ../types/parking/parking-area-code.raml
  ParkingStickerCode: !include ../types/parking/parking-sticker-code.raml
  ParkingStickerCodeObject: !include ../types/parking/parking-sticker-code-object.raml
  ParkingSticker: !include ../types/parking/parking-sticker.raml
