#%RAML 1.0 DataType
type: object
displayName: CarbonCreditMonthlyPaymentStatusObject
uses:
  types: ../../libraries/types.raml
properties:
  monthlyPaymentStatus:
    type: types.CarbonCreditMonthlyPaymentStatus
