#%RAML 1.0
title: SPAMD-UL
version: 0.0.2
mediaType: application/json
uses:
  types: ./libraries/types.raml
/api:
  /users:
    post:
      description: Add a new user
      body:
        application/json:
          type: types.User
          example: !include examples/user/post-users-request.json
      responses:
        201:
          description: Id for newly created account of user
          body:
            application/json:
              type: types.AccountIdObject
              example: !include examples/user/post-users-response.json
        400:
          description: Error adding user
    /{accountId}:
      get:
        description: Get the user with account with `accountId = {accountId}`
          responses:
            200:
              description: Requested user
              body:
                application/json:
                  type: types.User
                  example: !include ./examples/users/get-users-response.json
            400:
              description: Error getting user with account id
            404:
              description: User not found
  /parkings:
    post:
      description: Add a new parking sticker
      body:
        application/json:
          type: types.ParkingSticker
          example: !include examples/parking/post-parkings-request.json
      responses:
        201:
          description: Code for newly added parking sticker
          body:
            application/json:
              type: types.ParkingStickerCodeObject
              example: !include examples/parking/post-parkings-response.json
        400:
          description: Error adding parking sticker
        404:
          description: Account or parking area not found
