#%RAML 1.0
title: SPAMD-UL
version: 1.0.0
mediaType: application/json
uses:
  types: ./libraries/types.raml
/api:
  /users:
    post:
      description: Add a new user
      body:
        application/json:
          type: types.User
          example: !include examples/users/post-users-request.json
      responses:
        201:
          description: Id for newly created account of user
          body:
            application/json:
              type: types.AccountIdObject
              example: !include examples/users/post-users-response.json
        400:
          description: Error adding user
    /{accountId}:
      get:
        description: Get the user with account with `accountId = {accountId}`
        responses:
          200:
            description: Requested user
            body:
              application/json:
                type: types.User
                example: !include examples/users/get-users-response.json
          400:
            description: Error getting user
          404:
            description: User not found
  /parkings:
    post:
      description: Add a new parking sticker
      body:
        application/json:
          type: types.ParkingSticker
          examples:
            postal: !include examples/parkings/post-parkings-request-postal.json
            email: !include examples/parkings/post-parkings-request-email.json
      responses:
        201:
          description: Code for newly added parking sticker
          body:
            application/json:
              type: types.ParkingStickerCodeObject
              example: !include examples/parkings/post-parkings-response.json
        400:
          description: Error adding parking sticker
        404:
          description: Account or parking area not found
    /{parkingStickerCode}:
      /validate:
        get:
          description: Validate the parking sticker with code with `parkingStickerCode = {parkingStickerCode}` for current day
          responses:
            200:
              description: Access status of parking sticker code
              body:
                application/json:
                  type: types.AccessStatusObject
                  example: !include examples/parkings/get-parkings-validate-response.json
            400:
              description: Error validating parking sticker
            404:
              description: Parking sticker not found
  /offenseTypes:
    get:
      description: Collection of all possible offenseType types
      responses:
        200:
          description: All offenseType types
          body:
            application/json:
              type: types.OffenseType[]
              example: !include examples/offensetypes/get-offenseType-types-response.json
        400:
          description: Error getting offenseType types
  /offenseTypes:
    /validate:
      get:
        description: Check offenseTypes for the parking sticker
        body:
          application/json:
            type: types.OffenseValidation
            example: !include examples/offenseTypes/get-offenseTypes-validate-request.json
        responses:
          200:
            description: Offense type of parking sticker code
            body:
              application/json:
                type: types.OffenseType
                example: !include examples/offenseTypes/get-offenseTypes-validate-response.json
          400:
            description: Error getting offenseType type for parking sticker
          404:
            description: Parking sticker not found
  /cars:
    post:
      description: Add a new car
      body:
        application/json:
          type: types.Car
          example: !include examples/cars/post-cars-request.json
      responses:
        201:
          description: Car successfully added
        400:
          description: Error adding car
        404:
          description: Account not found
