#%RAML 1.0 DataType
type: object
displayName: Car
uses:
  types: ../../libraries/types.raml
properties:
  licensePlate:
    type: types.LicensePlate
    description: Valid license plate of car
  manufacturer:
    type: string
    description: Manufacturer of car
  model:
    type: string
    description: Model of car
  year:
    type: number
    description: Year of car
  consumptionType:
    type: types.ConsumptionType
