#%RAML 1.0 DataType
displayName: ConsumptionType
enum: [gourmande, économique, hybride économique, super économique, 0 pollution]
description: Valid consumption type (zero pollution means no car, it's associated with access passes without a car)
