#%RAML 1.0 DataType
displayName: ConsumptionType
enum: [greedy, economic, economical hydrid, super economical, 0 pollution]
description: Valid consumption type (0 pollution means no car, it's associated with access passes without a car)
